WARNING 2025-01-05 16:52:27,136 log Not Found: /favicon.ico
WARNING 2025-01-05 16:53:17,980 log Not Found: /favicon.ico
WARNING 2025-01-05 17:08:18,204 log Not Found: /favicon.ico
WARNING 2025-01-05 17:15:59,177 log Not Found: /favicon.ico
ERROR 2025-01-05 17:16:01,532 log Internal Server Error: /resource/
Traceback (most recent call last):
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: resources/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cybertea_project/cybertea_app/views.py", line 179, in resource
    return render(request, 'resources/resource.html', {'about': about})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/backends/django.py", line 109, in render
    reraise(exc, self.backend)
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/backends/django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: resources/base.html
WARNING 2025-01-05 17:22:58,762 log Not Found: /favicon.ico
WARNING 2025-01-05 17:23:43,295 log Not Found: /favicon.ico
WARNING 2025-01-05 17:24:16,469 log Not Found: /favicon.ico
WARNING 2025-01-05 17:30:47,934 log Not Found: /favicon.ico
WARNING 2025-01-05 17:39:54,591 log Not Found: /favicon.ico
WARNING 2025-01-05 17:45:10,256 log Not Found: /favicon.ico
WARNING 2025-01-05 17:45:17,987 log Not Found: /favicon.ico
WARNING 2025-01-05 17:46:52,643 log Not Found: /favicon.ico
WARNING 2025-01-05 17:47:42,802 log Not Found: /favicon.ico
WARNING 2025-01-05 17:59:34,238 log Not Found: /favicon.ico
ERROR 2025-01-05 18:10:00,914 log Internal Server Error: /forums/
Traceback (most recent call last):
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cybertea_project/cybertea_app/views.py", line 113, in forums
    return render(request, "cyberevents/forums.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/CyberTea App/cyberteaenv/lib/python3.11/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'forum_search' not found. 'forum_search' is not a valid view function or pattern name.
WARNING 2025-01-05 18:14:50,233 log Not Found: /favicon.ico
WARNING 2025-01-05 18:22:42,555 log Not Found: /favicon.ico
WARNING 2025-01-05 18:23:38,408 log Not Found: /favicon.ico
WARNING 2025-01-05 18:31:27,131 log Not Found: /favicon.ico
WARNING 2025-01-05 18:36:01,044 log Not Found: /favicon.ico
WARNING 2025-01-05 18:36:57,480 log Not Found: /favicon.ico
